import { useState, useEffect } from "react";
import { X, Download, Mail, FileText, Trophy, Sparkles, Loader2, Send } from "lucide-react";
import { type StoredLesson } from "@/hooks/use-lessons-store";
import { useSettings } from "@/hooks/use-settings";
import type { QuizResult } from "@/components/quiz-view";

interface LearningReportModalProps {
  lesson: StoredLesson;
  quizResult: QuizResult;
  open: boolean;
  onClose: () => void;
  shareId?: string | null;
}

export function LearningReportModal({ lesson, quizResult, open, onClose, shareId = null }: LearningReportModalProps) {
  const { getLlmConfig, isConfigured } = useSettings();
  const [studentName, setStudentName] = useState("");
  const [studentEmail, setStudentEmail] = useState("");
  const [teacherEmail, setTeacherEmail] = useState("");
  const [notes, setNotes] = useState("");
  const [aiReflection, setAiReflection] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [emailCapable, setEmailCapable] = useState<boolean | null>(null);
  const [sending, setSending] = useState(false);
  const [sendResult, setSendResult] = useState<{ ok: boolean; message: string } | null>(null);

  useEffect(() => {
    if (!open) return;
    fetch("/api/email-capability")
      .then((r) => r.json())
      .then((d) => setEmailCapable(Boolean(d.available)))
      .catch(() => setEmailCapable(false));
  }, [open]);

  if (!open) return null;

  const now = new Date();
  const dateStr = now.toLocaleDateString(undefined, {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  const { score, total, missedQuestions } = quizResult;
  const scoreText = `${score}/${total} (${Math.round((score / total) * 100)}%)`;

  const conceptList = lesson.keyConcepts
    .map((c) => `- **${c.term}**: ${c.definition}`)
    .join("\n");

  const missedList = missedQuestions.length > 0
    ? missedQuestions.map((q) => `- ${q.question} _(answered: ${q.yourAnswer}, correct: ${q.correctAnswer})_`).join("\n")
    : null;

  const buildReport = (): string => {
    const name = studentName.trim() || "Student";
    const lines = [
      `# Learning Report`,
      ``,
      `**Lesson:** ${lesson.title}`,
      `**Student:** ${name}`,
      `**Date:** ${dateStr}`,
      `**Quiz Score:** ${scoreText}`,
      ``,
    ];

    if (missedList) {
      lines.push(`## Concepts to Review`, ``, missedList, ``);
    }

    lines.push(`## Key Concepts Covered`, ``, conceptList, ``);

    if (aiReflection) {
      lines.push(`## AI-Generated Reflection`, ``, aiReflection, ``);
    }

    if (notes.trim()) {
      lines.push(`## My Reflections`, ``, notes.trim(), ``);
    }

    lines.push(`---`, `*Generated by SmartTextbook*`);
    return lines.join("\n");
  };

  const handleGenerateReflection = async () => {
    setGenerating(true);
    setGenerateError(null);
    try {
      const body: Record<string, unknown> = {
        score,
        total,
        missedQuestions,
        studentNotes: notes,
      };
      if (isConfigured) {
        body.llmConfig = getLlmConfig();
      }

      const res = await fetch(`/api/shared/${shareId}/generate-report`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`);
      setAiReflection(data.reflection);
    } catch (err: unknown) {
      setGenerateError(err instanceof Error ? err.message : "Failed to generate reflection");
    }
    setGenerating(false);
  };

  const downloadMarkdown = () => {
    const content = buildReport();
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `learning-report-${lesson.title.slice(0, 40).replace(/\s+/g, "-").toLowerCase()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleServerEmail = async () => {
    const toList = [studentEmail.trim(), teacherEmail.trim()].filter(Boolean);
    if (toList.length === 0) return;
    setSending(true);
    setSendResult(null);
    try {
      const name = studentName.trim() || "Student";
      const res = await fetch(`/api/shared/${shareId}/email-report`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          to: toList,
          subject: `Learning Report: ${lesson.title} — ${name}`,
          body: buildReport(),
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`);
      setSendResult({ ok: true, message: "Report sent successfully!" });
    } catch (err: unknown) {
      setSendResult({ ok: false, message: err instanceof Error ? err.message : "Failed to send email" });
    }
    setSending(false);
  };



  const canEmail = Boolean(studentEmail.trim() || teacherEmail.trim());
  const serverEmailAvailable = emailCapable === true;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-card border border-border rounded-2xl shadow-2xl w-full max-w-lg max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border shrink-0">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            <h2 className="text-base font-serif font-bold text-foreground">Learning Report</h2>
          </div>
          <button onClick={onClose} className="text-muted-foreground hover:text-foreground transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-4">
          {/* Quiz score banner */}
          <div className="flex items-center gap-3 p-4 rounded-xl bg-primary/8 border border-primary/20">
            <Trophy className="w-6 h-6 text-primary shrink-0" />
            <div>
              <p className="text-sm font-semibold text-foreground">Quiz Score</p>
              <p className="text-xs text-muted-foreground">
                {score} / {total} correct ({Math.round((score / total) * 100)}%)
              </p>
            </div>
          </div>

          {/* Missed concepts */}
          {missedQuestions.length > 0 && (
            <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 dark:bg-amber-950/20 dark:border-amber-800">
              <p className="text-xs font-semibold text-amber-800 dark:text-amber-400 mb-2">
                Concepts to Review ({missedQuestions.length})
              </p>
              <ul className="space-y-1">
                {missedQuestions.map((q, i) => (
                  <li key={i} className="text-xs text-amber-700 dark:text-amber-300">
                    <span className="font-medium">{q.question}</span>
                    <span className="text-amber-500 dark:text-amber-500"> — correct: {q.correctAnswer}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Student name */}
          <div>
            <label className="block text-xs font-semibold text-muted-foreground mb-1.5">Your Name</label>
            <input
              type="text"
              placeholder="Enter your name"
              value={studentName}
              onChange={(e) => setStudentName(e.target.value)}
              className="w-full border border-border rounded-xl px-3 py-2.5 text-sm bg-background outline-none focus:border-primary/60 transition-colors"
            />
          </div>

          {/* Reflections */}
          <div>
            <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
              My Reflections <span className="font-normal">(optional)</span>
            </label>
            <textarea
              placeholder="What did you learn? What was challenging? What will you apply?"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              className="w-full border border-border rounded-xl px-3 py-2.5 text-sm bg-background outline-none focus:border-primary/60 transition-colors resize-none"
            />
          </div>

          {/* AI reflection */}
          <div className="border border-border rounded-xl overflow-hidden">
            <div className="flex items-center justify-between px-4 py-3 bg-muted/40">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" />
                <span className="text-xs font-semibold text-foreground">AI-Generated Reflection</span>
              </div>
              <button
                onClick={handleGenerateReflection}
                disabled={generating || !shareId}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary text-primary-foreground text-xs font-semibold disabled:opacity-50 hover:bg-primary/90 transition-colors"
              >
                {generating ? <Loader2 className="w-3 h-3 animate-spin" /> : <Sparkles className="w-3 h-3" />}
                {generating ? "Generating…" : aiReflection ? "Regenerate" : "Generate"}
              </button>
            </div>
            <div className="px-4 py-3 min-h-[60px]">
              {aiReflection ? (
                <p className="text-sm text-foreground leading-relaxed">{aiReflection}</p>
              ) : generateError ? (
                <p className="text-xs text-destructive">{generateError}</p>
              ) : (
                <p className="text-xs text-muted-foreground italic">
                  {shareId
                    ? "Click Generate to get a personalized AI reflection based on your quiz performance."
                    : "AI reflection is available on shared lesson pages."}
                </p>
              )}
            </div>
          </div>

          {/* Email section — only shown when server email is configured */}
          {serverEmailAvailable && (
            <div className="pt-2 border-t border-border">
              <div className="flex items-center gap-2 mb-3">
                <Mail className="w-4 h-4 text-muted-foreground" />
                <p className="text-xs font-semibold text-muted-foreground">Send Report by Email</p>
              </div>
              <div className="space-y-2">
                <input
                  type="email"
                  placeholder="Your email address"
                  value={studentEmail}
                  onChange={(e) => setStudentEmail(e.target.value)}
                  className="w-full border border-border rounded-xl px-3 py-2.5 text-sm bg-background outline-none focus:border-primary/60 transition-colors"
                />
                <input
                  type="email"
                  placeholder="Teacher's email address"
                  value={teacherEmail}
                  onChange={(e) => setTeacherEmail(e.target.value)}
                  className="w-full border border-border rounded-xl px-3 py-2.5 text-sm bg-background outline-none focus:border-primary/60 transition-colors"
                />
                <p className="text-xs text-muted-foreground">
                  Enter one or both email addresses to receive your learning report.
                </p>
                {sendResult && (
                  <p className={`text-xs font-medium ${sendResult.ok ? "text-green-600" : "text-destructive"}`}>
                    {sendResult.message}
                  </p>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Footer buttons */}
        <div className="flex gap-2 px-6 py-4 border-t border-border shrink-0">
          <button
            onClick={downloadMarkdown}
            className="flex-1 inline-flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl border border-border bg-card text-sm font-semibold text-foreground hover:bg-muted transition-colors"
          >
            <Download className="w-4 h-4" /> Download
          </button>
          {serverEmailAvailable && (
            <button
              onClick={handleServerEmail}
              disabled={!canEmail || sending}
              className="flex-1 inline-flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold disabled:opacity-40 hover:bg-primary/90 transition-colors"
            >
              {sending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
              {sending ? "Sending…" : "Send Email"}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
