import { useState } from "react";
import { X, Download, Mail, FileText, Trophy } from "lucide-react";
import { type StoredLesson } from "@/hooks/use-lessons-store";

interface LearningReportModalProps {
  lesson: StoredLesson;
  quizScore: { score: number; total: number } | null;
  open: boolean;
  onClose: () => void;
}

export function LearningReportModal({ lesson, quizScore, open, onClose }: LearningReportModalProps) {
  const [studentName, setStudentName] = useState("");
  const [studentEmail, setStudentEmail] = useState("");
  const [teacherEmail, setTeacherEmail] = useState("");
  const [notes, setNotes] = useState("");

  if (!open) return null;

  const now = new Date();
  const dateStr = now.toLocaleDateString(undefined, {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  const scoreText = quizScore
    ? `${quizScore.score}/${quizScore.total} (${Math.round((quizScore.score / quizScore.total) * 100)}%)`
    : "Quiz not completed";

  const conceptList = lesson.keyConcepts
    .map((c) => `- **${c.term}**: ${c.definition}`)
    .join("\n");

  const buildReport = (): string => {
    const name = studentName.trim() || "Student";
    const lines = [
      `# Learning Report`,
      ``,
      `**Lesson:** ${lesson.title}`,
      `**Student:** ${name}`,
      `**Date:** ${dateStr}`,
      `**Quiz Score:** ${scoreText}`,
      ``,
      `## Summary`,
      ``,
      lesson.summary,
      ``,
      `## Key Concepts Covered`,
      ``,
      conceptList,
    ];

    if (notes.trim()) {
      lines.push(``, `## My Reflections`, ``, notes.trim());
    }

    lines.push(``, `---`, `*Generated by SmartTextbook — smartextbook.replit.app*`);
    return lines.join("\n");
  };

  const downloadMarkdown = () => {
    const content = buildReport();
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `learning-report-${lesson.title.slice(0, 40).replace(/\s+/g, "-").toLowerCase()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const emailReport = () => {
    const name = studentName.trim() || "Student";
    const content = buildReport();
    const subject = encodeURIComponent(`Learning Report: ${lesson.title} — ${name}`);
    const body = encodeURIComponent(content);
    const toList = [teacherEmail.trim(), studentEmail.trim()].filter(Boolean).join(",");
    const mailto = `mailto:${toList}?subject=${subject}&body=${body}`;
    window.open(mailto, "_blank");
  };

  const canEmail = studentEmail.trim() || teacherEmail.trim();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-card border border-border rounded-2xl shadow-2xl w-full max-w-lg max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border shrink-0">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            <h2 className="text-base font-serif font-bold text-foreground">Learning Report</h2>
          </div>
          <button onClick={onClose} className="text-muted-foreground hover:text-foreground transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-4">
          {/* Quiz score banner */}
          {quizScore && (
            <div className="flex items-center gap-3 p-4 rounded-xl bg-primary/8 border border-primary/20">
              <Trophy className="w-6 h-6 text-primary shrink-0" />
              <div>
                <p className="text-sm font-semibold text-foreground">Quiz Score</p>
                <p className="text-xs text-muted-foreground">
                  {quizScore.score} / {quizScore.total} correct ({Math.round((quizScore.score / quizScore.total) * 100)}%)
                </p>
              </div>
            </div>
          )}

          {/* Student name */}
          <div>
            <label className="block text-xs font-semibold text-muted-foreground mb-1.5">Your Name</label>
            <input
              type="text"
              placeholder="Enter your name"
              value={studentName}
              onChange={(e) => setStudentName(e.target.value)}
              className="w-full border border-border rounded-xl px-3 py-2.5 text-sm bg-background outline-none focus:border-primary/60 transition-colors"
            />
          </div>

          {/* Reflections */}
          <div>
            <label className="block text-xs font-semibold text-muted-foreground mb-1.5">
              My Reflections <span className="font-normal">(optional)</span>
            </label>
            <textarea
              placeholder="What did you learn? What was challenging? What will you apply?"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              className="w-full border border-border rounded-xl px-3 py-2.5 text-sm bg-background outline-none focus:border-primary/60 transition-colors resize-none"
            />
          </div>

          {/* Email fields */}
          <div className="pt-2 border-t border-border">
            <div className="flex items-center gap-2 mb-3">
              <Mail className="w-4 h-4 text-muted-foreground" />
              <p className="text-xs font-semibold text-muted-foreground">
                Email Report (opens your email app)
              </p>
            </div>
            <div className="space-y-2">
              <input
                type="email"
                placeholder="Your email address"
                value={studentEmail}
                onChange={(e) => setStudentEmail(e.target.value)}
                className="w-full border border-border rounded-xl px-3 py-2.5 text-sm bg-background outline-none focus:border-primary/60 transition-colors"
              />
              <input
                type="email"
                placeholder="Teacher's email address"
                value={teacherEmail}
                onChange={(e) => setTeacherEmail(e.target.value)}
                className="w-full border border-border rounded-xl px-3 py-2.5 text-sm bg-background outline-none focus:border-primary/60 transition-colors"
              />
              <p className="text-xs text-muted-foreground">
                Fill in one or both emails. Your email app will open with the report ready to send.
              </p>
            </div>
          </div>
        </div>

        {/* Footer buttons */}
        <div className="flex gap-2 px-6 py-4 border-t border-border shrink-0">
          <button
            onClick={downloadMarkdown}
            className="flex-1 inline-flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl border border-border bg-card text-sm font-semibold text-foreground hover:bg-muted transition-colors"
          >
            <Download className="w-4 h-4" /> Download
          </button>
          <button
            onClick={emailReport}
            disabled={!canEmail}
            className="flex-1 inline-flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold disabled:opacity-40 hover:bg-primary/90 transition-colors"
          >
            <Mail className="w-4 h-4" /> Email Report
          </button>
        </div>
      </div>
    </div>
  );
}
